export const TaskActionTypes = {
    ADD_TASK_TO_LIST : 'ADD_TASK_TO_LIST',
    REMOVE_TASK_FROM_LIST : 'REMOVE_TASK_FROM_LIST',
    CONFIRM_MODIFICATION : 'CONFIRM_MODIFICATION',
    CHANGE_EDITABLE_STATE : 'CHANGE_EDITABLE_STATE'
};